(()=>{'use strict';
const DATA='data/intelligence_brain.json';
const TYPE_COLORS={sanctions:'#ff5368',military_action_against:'#ff8a3d',negotiates_with:'#39ff88',trades_with:'#ffc857',economic_action_toward:'#ffc857',technology_action_toward:'#5da8ff',energy_action_toward:'#4de0c1',cyber_action_against:'#b46cff',political_action_toward:'#c58cff',evidence:'#8aa9bd',default:'#5da8ff'};
const TYPE_LABELS={sanctions:'SANCTIONS',military_action_against:'MILITARY',negotiates_with:'DIPLOMATIC',trades_with:'TRADE',economic_action_toward:'ECONOMIC',technology_action_toward:'TECHNOLOGY',energy_action_toward:'ENERGY',cyber_action_against:'CYBER',political_action_toward:'POLITICAL'};
let data=null,svg=null,enabled=true,lastSignature='',renderQueued=false;
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function ensure(){const graph=document.getElementById('graph');if(!graph)return false;if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='gp-semantic-layer';Object.assign(svg.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'7',pointerEvents:'none',display:enabled?'block':'none'});graph.appendChild(svg);const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');svg.appendChild(defs);for(const [k,c] of Object.entries(TYPE_COLORS)){const m=document.createElementNS('http://www.w3.org/2000/svg','marker');m.id='gp-arrow-'+k;m.setAttribute('markerWidth','7');m.setAttribute('markerHeight','7');m.setAttribute('refX','6');m.setAttribute('refY','3.5');m.setAttribute('orient','auto');m.setAttribute('markerUnits','strokeWidth');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d','M0,0 L7,3.5 L0,7 z');p.setAttribute('fill',c);m.appendChild(p);defs.appendChild(m)}}return true}
function typeOf(e){const ts=Array.isArray(e?.types)?e.types.filter(Boolean):[];if(ts.length)return String(ts[0]);const r=String(e?.relationship||'').toLowerCase();for(const k of Object.keys(TYPE_LABELS))if(r.includes(k)||r.includes(TYPE_LABELS[k].toLowerCase()))return k;return 'evidence'}
function labelMap(){const m=new Map();document.querySelectorAll('.gp-label').forEach(el=>{const r=el.getBoundingClientRect();m.set(el.textContent.trim(),{x:r.left+r.width/2,y:r.top+r.height/2})});return m}
function updateLegend(){let box=document.getElementById('gp-semantic-legend');if(!box){box=document.createElement('div');box.id='gp-semantic-legend';Object.assign(box.style,{position:'fixed',right:'14px',bottom:'14px',zIndex:'40',background:'rgba(2,7,12,.9)',border:'1px solid #193244',borderRadius:'10px',padding:'8px 10px',font:'800 8px system-ui',letterSpacing:'.08em',color:'#b8cbd8',backdropFilter:'blur(12px)',pointerEvents:'none',maxWidth:'300px'}) ;document.body.appendChild(box)}const present=new Set();(data?.edges||[]).forEach(e=>present.add(typeOf(e)));box.innerHTML='<div style="color:#39ff88;margin-bottom:6px">SEMANTIC RELATIONSHIPS</div>'+Object.keys(TYPE_LABELS).filter(k=>present.has(k)).map(k=>`<span style="display:inline-block;margin:2px 6px 2px 0;color:${TYPE_COLORS[k]}">● ${TYPE_LABELS[k]}</span>`).join('')+'<div style="margin-top:5px;color:#8198aa;font-weight:600;letter-spacing:0">Directional lines are source-backed actor → target/context relationships.</div>'}
function render(){renderQueued=false;if(!ensure()||!data)return;if(!enabled){svg.style.display='none';return}svg.style.display='block';while(svg.firstChild?.nextSibling)svg.removeChild(svg.lastChild);const nodes=Array.isArray(data.nodes)?data.nodes:[];const ids=new Map(nodes.map(n=>[String(n.id),String(n.label||n.name||n.id)]));const labels=labelMap();const edges=Array.isArray(data.edges)?data.edges:[];const used=new Set();const parts=[];for(const e of edges){const s=String(e?.source?.id??e?.source??''),t=String(e?.target?.id??e?.target??'');const a=labels.get(ids.get(s)||''),b=labels.get(ids.get(t)||'');if(!a||!b||s===t)continue;const type=typeOf(e),key=s+'|'+t+'|'+type;if(used.has(key))continue;used.add(key);const color=TYPE_COLORS[type]||TYPE_COLORS.default;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('stroke',color);line.setAttribute('stroke-width',type==='evidence'?'1':'1.8');line.setAttribute('stroke-opacity',type==='evidence'?'.18':'.72');if(type!=='evidence')line.setAttribute('marker-end','url(#gp-arrow-'+(TYPE_COLORS[type]?type:'default')+')');svg.appendChild(line);parts.push(type)}const sig=parts.sort().join(',');if(sig!==lastSignature){lastSignature=sig;updateLegend()}}
function queue(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(render)}
function setEnabled(next){enabled=!!next;if(svg)svg.style.display=enabled?'block':'none';if(enabled)queue();const flow=document.getElementById('flow');if(flow)flow.setAttribute('aria-pressed',String(enabled))}
function bindControls(){const flow=document.getElementById('flow');if(!flow||flow.dataset.gpSemantic==='1')return;if(flow.dataset.gpSemantic==='1')return;flow.dataset.gpSemantic='1';enabled=flow.classList.contains('active');flow.setAttribute('aria-pressed',String(enabled));flow.addEventListener('click',()=>{setEnabled(flow.classList.contains('active'))},{capture:true});document.addEventListener('gp:relationships',e=>setEnabled(e?.detail?.enabled!==false));}
async function load(){try{const r=await fetch(DATA+'?v='+Date.now(),{cache:'no-store'});if(r.ok){data=await r.json();lastSignature='';updateLegend();queue()}}catch(_){}}
function watchLabels(){const graph=document.getElementById('graph');if(!graph)return;const observer=new MutationObserver(()=>queue());observer.observe(graph,{childList:true,subtree:true,attributes:true,attributeFilter:['style','class']})}
function init(){bindControls();ensure();load();watchLabels();window.addEventListener('resize',queue,{passive:true});setTimeout(queue,350)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();