(()=>{'use strict';
const DATA='data/intelligence_brain.json';
const TYPE_COLORS={sanctions:'#ff5368',military_action_against:'#ff8a3d',negotiates_with:'#39ff88',trades_with:'#ffc857',economic_action_toward:'#ffc857',technology_action_toward:'#5da8ff',energy_action_toward:'#4de0c1',cyber_action_against:'#b46cff',political_action_toward:'#c58cff',evidence:'#8aa9bd',default:'#5da8ff'};
const TYPE_LABELS={sanctions:'SANCTIONS',military_action_against:'MILITARY',negotiates_with:'DIPLOMATIC',trades_with:'TRADE',economic_action_toward:'ECONOMIC',technology_action_toward:'TECHNOLOGY',energy_action_toward:'ENERGY',cyber_action_against:'CYBER',political_action_toward:'POLITICAL'};
let data=null,canvas=null,gl=null,program=null,enabled=true,queued=false,lastSig='',w=1,h=1;
const $=id=>document.getElementById(id);
function hex(s){const m=String(s||'').replace('#','');return[m.slice(0,2),m.slice(2,4),m.slice(4,6)].map(x=>parseInt(x||'00',16)/255)}
function typeOf(e){const ts=Array.isArray(e?.types)?e.types.filter(Boolean):[];if(ts.length)return String(ts[0]);const r=String(e?.relationship||'').toLowerCase();for(const k of Object.keys(TYPE_LABELS))if(r.includes(k)||r.includes(TYPE_LABELS[k].toLowerCase()))return k;return'evidence'}
function ensure(){const graph=$('graph');if(!graph)return false;if(canvas)return true;canvas=document.createElement('canvas');canvas.id='gp-semantic-webgl';Object.assign(canvas.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'7',pointerEvents:'none',display:'block'});graph.appendChild(canvas);gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false});if(!gl)return false;const vs='attribute vec2 aPosition;attribute vec4 aColor;uniform vec2 uScale;varying vec4 vColor;void main(){gl_Position=vec4(aPosition*uScale-vec2(1.0),0.0,1.0);vColor=aColor;}';const fs='precision mediump float;varying vec4 vColor;void main(){gl_FragColor=vColor;}';const compile=(t,s)=>{const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x};program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));resize();return true}
function labelMap(){const m=new Map();document.querySelectorAll('.gp-label').forEach(el=>{const r=el.getBoundingClientRect();m.set(el.textContent.trim(),{x:r.left+r.width/2,y:r.top+r.height/2})});return m}
function updateLegend(){let box=$('gp-semantic-legend');if(!box){box=document.createElement('div');box.id='gp-semantic-legend';Object.assign(box.style,{position:'fixed',right:'14px',bottom:'14px',zIndex:'40',background:'rgba(2,7,12,.9)',border:'1px solid #193244',borderRadius:'10px',padding:'8px 10px',font:'800 8px system-ui',letterSpacing:'.08em',color:'#b8cbd8',backdropFilter:'blur(12px)',pointerEvents:'none',maxWidth:'300px'});document.body.appendChild(box)}const present=new Set((data?.edges||[]).map(typeOf));box.innerHTML='<div style="color:#39ff88;margin-bottom:6px">SEMANTIC RELATIONSHIPS</div>'+Object.keys(TYPE_LABELS).filter(k=>present.has(k)).map(k=>`<span style="display:inline-block;margin:2px 6px 2px 0;color:${TYPE_COLORS[k]}">● ${TYPE_LABELS[k]}</span>`).join('')+'<div style="margin-top:5px;color:#8198aa;font-weight:600;letter-spacing:0">WebGL directional actor → target/context relationships.</div>'}
function render(){queued=false;if(!ensure()||!data)return;if(!enabled){gl.clear(gl.COLOR_BUFFER_BIT);canvas.style.display='none';return}canvas.style.display='block';const nodes=Array.isArray(data.nodes)?data.nodes:[],ids=new Map(nodes.map(n=>[String(n.id),String(n.label||n.name||n.id)])),labels=labelMap(),edges=Array.isArray(data.edges)?data.edges:[],v=[];const seen=new Set();for(const e of edges){const s=String(e?.source?.id??e?.source??''),t=String(e?.target?.id??e?.target??'');const a=labels.get(ids.get(s)||''),b=labels.get(ids.get(t)||'');if(!a||!b||s===t)continue;const type=typeOf(e),key=s+'|'+t+'|'+type;if(seen.has(key))continue;seen.add(key);const c=hex(TYPE_COLORS[type]||TYPE_COLORS.default),ax=a.x,ay=a.y,bx=b.x,by=b.y,dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy)||1,nx=dx/len,ny=dy/len,px=-ny,py=nx;const arrow=type==='evidence'?0:7;const tx=bx-nx*10,ty=by-ny*10,half=arrow?4:0;const add=(x,y)=>v.push((x/w)*2,(1-y/h)*2,c[0],c[1],c[2],type==='evidence'?.18:.72);add(ax,ay);add(tx,ty);if(arrow){add(tx+px*half,ty+py*half);add(bx-nx*2,by-ny*2);add(tx-px*half,ty-py*half);add(bx-nx*2,by-ny*2)}}gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(program);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.DYNAMIC_DRAW);const p=gl.getAttribLocation(program,'aPosition'),c=gl.getAttribLocation(program,'aColor');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(c);gl.vertexAttribPointer(c,4,gl.FLOAT,false,24,8);gl.uniform2f(gl.getUniformLocation(program,'uScale'),1,1);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.lineWidth(1);gl.drawArrays(gl.LINES,0,v.length/6);lastSig=[v.length,edges.length].join(':');updateLegend()}
function queue(){if(queued)return;queued=true;requestAnimationFrame(render)}
function setEnabled(next){enabled=!!next;if(canvas)canvas.style.display=enabled?'block':'none';if(enabled)queue();const flow=$('flow');if(flow)flow.setAttribute('aria-pressed',String(enabled))}
function bindControls(){const flow=$('flow');if(!flow||flow.dataset.gpSemantic==='1')return;flow.dataset.gpSemantic='1';enabled=flow.classList.contains('active');flow.setAttribute('aria-pressed',String(enabled));flow.addEventListener('click',()=>setEnabled(flow.classList.contains('active')),{capture:true});document.addEventListener('gp:relationships',e=>setEnabled(e?.detail?.enabled!==false))}
function resize(){if(!canvas||!gl)return;w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(w*d);canvas.height=Math.floor(h*d);canvas.style.width=w+'px';canvas.style.height=h+'px';gl.viewport(0,0,canvas.width,canvas.height);queue()}
async function load(){try{const r=await fetch(DATA+'?v='+Date.now(),{cache:'no-store'});if(r.ok){data=await r.json();lastSig='';updateLegend();queue()}}catch(_){}}
function watch(){const graph=$('graph');if(!graph)return;new MutationObserver(queue).observe(graph,{childList:true,subtree:true,attributes:true,attributeFilter:['style','class']})}
function init(){bindControls();if(!ensure())return;load();watch();addEventListener('resize',resize,{passive:true});setTimeout(queue,350)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();