/* Global Pulse Intelligence Web — stable mobile renderer + live source resolver. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),GRAPH='data/intelligence_graph.json',SNAP='data/snapshot.json',LIVE='data/live_articles.json';
/* OPTION D Abyss Current: bioluminescent cooler-shifted kind palette. Semantics kept: red sanctions/conflict, orange military, green negotiation, gold trade, blue tech, teal energy, purple cyber/political. */
const NODE_COLORS={actor:'#4fd2ff',political:'#b78cff',economic:'#ffc857',strategic:'#46d8ff',military:'#ff5d6e',resource:'#3df097',oil:'#ff8a3d'};
const EDGE_COLORS={conflict:'#ff5d6e',military:'#ff7a45',political:'#b78cff',economic:'#ffc857',strategic:'#46d8ff',security:'#4fa8ff',resource:'#3df097',oil:'#ff8a3d',energy:'#2fe8c8',diplomatic:'#9b8cff',trade:'#ffd166',graph:'#4fd2ff',general:'#5da8ff'};
/* ABYSS GRAPH (JS-owned, part 1 of 2): bioluminescent core+halo nodes, major-hub
   pulse, selection crosshair + neighbor spotlight, stepped link widths, drifting
   particle flow, zoom-aware capped labels. Partner DOM hooks (HTML/CSS-owned):
   .abyss-crosshair[data-abyss="crosshair"], .node-label[data-abyss="label"].
   Legend color semantics unchanged. No new deps/hosts. */
const ABYSS={maxLabels:60,farLabels:16,farDist:1050,haloScale:1.9,haloOpacity:.22,dimOpacity:.22};
const reducedMotion=()=>typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
const isMajor=n=>/\b(united states|\bu\.s\.|\busa\b|china|\bprc\b)/i.test(String(n&&n.label||'')+' '+String(n&&n.id||''));
function abyssSize(n,sel,isNb){const m=Number(n&&n.mentions)||0;const base=Math.max(12,Math.min(30,12+Math.sqrt(Math.max(1,m))*2));const maj=isMajor(n)?1.6:1;if(!sel)return base*maj;if(String(n.id)===String(sel.id))return Math.max(16,Math.min(34,base*1.15))*maj;if(isNb)return Math.max(9,Math.min(25,9+Math.sqrt(Math.max(1,m))*1.7))*maj;return Math.max(7,Math.min(16,base*.62))}
function abyssLinkWidth(e){const w=Math.max(1,Number(e&&e.weight)||1);const ev=Array.isArray(e&&e.evidence)?e.evidence.length:0;const s=Math.max(w,Math.min(12,ev||w));if(s<=2)return 3;if(s<=4)return 5;if(s<=8)return 7.5;return 10}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const href=v=>{try{const raw=String(v||'').trim();if(!/^https?:\/\//i.test(raw))return'';const u=new URL(raw);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const normTitle=v=>String(v||'').toLowerCase().replace(/[‘’“”]/g,"'").replace(/[^a-z0-9]+/g,' ').trim();
const ends=e=>[String(e.source?.id??e.source??e.sid??''),String(e.target?.id??e.target??e.tid??'')];
const evidenceUrl=e=>href(e?.original_link)||href(e?.url)||href(e?.sourceUrl)||href(e?.source_url)||href(e?.link)||href(e?.credit?.source_url)||'';
const evidenceClean=a=>Array.isArray(a)?a.filter(x=>x&&((x.title&&String(x.title).trim())||evidenceUrl(x))).slice(0,12):[];
let liveByTitle=new Map(),liveBySourceTitle=new Map();
function indexLive(d){liveByTitle=new Map();liveBySourceTitle=new Map();const a=Array.isArray(d?.articles)?d.articles:[];for(const x of a){const u=evidenceUrl(x);const t=normTitle(x?.title);const s=normTitle(x?.source||x?.sourceLabel||x?.publisher);if(u&&t){if(!liveByTitle.has(t))liveByTitle.set(t,u);if(s)liveBySourceTitle.set(s+'|'+t,u)}}}
function resolveUrl(e){const direct=evidenceUrl(e);if(direct)return direct;const t=normTitle(e?.title),s=normTitle(e?.source);return liveBySourceTitle.get(s+'|'+t)||liveByTitle.get(t)||''}
function enrichEvidence(e){if(!e)return e;const u=resolveUrl(e);if(u&&!e.url)e.url=u;return e}
async function get(path){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function normalize(d){const g=d?.intelligenceGraph&&typeof d.intelligenceGraph==='object'?d.intelligenceGraph:null,r=g||d||{};const nodes=(Array.isArray(r.nodes)?r.nodes:[]).map((n,i)=>({...n,id:String(n.id||'node-'+i),label:String(n.label||n.name||n.title||n.id||'Entity '+(i+1)),kind:String(n.kind||'actor').toLowerCase(),mentions:Number(n.mentions)||0,evidence:evidenceClean(n.evidence).map(enrichEvidence)}));const valid=new Set(nodes.map(n=>n.id));const links=(Array.isArray(r.edges)?r.edges:[]).map(e=>{const[s,t]=ends(e);return{...e,source:s,target:t,sid:s,tid:t,weight:Math.max(1,Number(e.weight)||1),types:Array.isArray(e.types)?e.types.map(String):[],relationship:String(e.relationship||'Both entities are referenced in the same public evidence record.'),evidence:evidenceClean(e.evidence).map(enrichEvidence)}}).filter(e=>valid.has(e.source)&&valid.has(e.target)&&e.source!==e.target);return{nodes,links,updatedAt:r.updatedAt||d?.updatedAt||'',method:r.method||'Evidence-backed public reporting graph',caution:r.caution||''}}
async function load(){let live={};try{live=await get(LIVE);indexLive(live)}catch{indexLive({})}try{const g=normalize(await get(GRAPH));if(g.nodes.length)return g}catch{}return normalize(await get(SNAP))}
function edgeColor(e){const t=(e.types||[]).map(x=>String(x).toLowerCase()),r=String(e.relationship||'').toLowerCase();for(const k of ['conflict','military','political','economic','strategic','security','resource','oil','energy','diplomatic','trade'])if(t.some(x=>x.includes(k))||r.includes(k))return EDGE_COLORS[k];return EDGE_COLORS.general}
function showLoadingError(e){const el=$('loading');if(!el)return;el.style.display='grid';el.style.pointerEvents='auto';el.setAttribute('aria-hidden','false');el.innerHTML='<div style="text-align:center;padding:24px;max-width:520px"><b>INTELLIGENCE WEB DATA ERROR</b><br><small>'+esc(e?.message||'Unable to initialize the intelligence graph.')+'</small><br><button id="loading-retry" type="button" style="margin-top:12px">RETRY</button></div>';const b=$('loading-retry');if(b)b.onclick=()=>location.reload()}
function hideLoading(){const el=$('loading');if(!el)return;el.style.display='none';el.style.pointerEvents='none';el.setAttribute('aria-hidden','true')}
async function main(base){let active={nodes:[],links:[]},selected=null,dialog=false,filter='all',period='all',query='',fitTimer=0,controls=true,orbit=false,orbitFrame=0,paused=false,relationships=true,labelFrame=0,pulseThreshold=0,pulseFrame=0;
const peer=(e,id)=>{const[a,b]=ends(e);return a===String(id)?b:a};const related=n=>active.links.filter(e=>ends(e).includes(String(n.id)));
const neighborIds=()=>{if(!selected)return new Set();const s=new Set([String(selected.id)]);for(const e of related(selected))s.add(peer(e,selected.id));return s};
function styles(){const g=window.__gpGraph;if(!g)return;const nb=neighborIds();g.nodeColor(n=>{const c=NODE_COLORS[n.kind]||NODE_COLORS.actor;if(!selected)return c;if(String(n.id)===String(selected.id))return '#ffffff';return nb.has(String(n.id))?c:'#263844'});g.nodeVal(n=>abyssSize(n,selected,selected&&nb.has(String(n.id))&&String(n.id)!==String(selected.id)));try{g.nodeOpacity(n=>!selected?1:(nb.has(String(n.id))?1:ABYSS.dimOpacity))}catch{}g.linkColor(e=>selected&&ends(e).includes(String(selected.id))?'#ffffff':edgeColor(e));g.linkOpacity(e=>selected?(ends(e).includes(String(selected.id))?.98:ABYSS.dimOpacity):.9);g.linkWidth(abyssLinkWidth)}
/* Bioluminescent halo: clone the force-graph mesh (no new THREE dependency),
   tint a translucent shell in the legend color around the bright core. Static
   geometry under prefers-reduced-motion; only the shell scale breathes. */
function ensureHalo(n){try{const o=n.__threeObj;if(!o||typeof o.clone!=='function'||!o.material||typeof o.add!=='function')return null;if(n.__abyssHalo&&n.__abyssHaloHost===o)return n.__abyssHalo;const c=NODE_COLORS[n.kind]||NODE_COLORS.actor;try{if(o.material.emissive&&typeof o.material.emissive.set==='function'){o.material.emissive.set(c);o.material.emissiveIntensity=.55}}catch{}let halo=null;try{halo=o.clone(false)}catch{return null}try{halo.material=o.material.clone();halo.material.transparent=true;halo.material.opacity=ABYSS.haloOpacity;halo.material.depthWrite=false;if('emissiveIntensity' in halo.material)halo.material.emissiveIntensity=.9;halo.scale.setScalar(ABYSS.haloScale);halo.raycast=()=>{};o.add(halo)}catch{return null}n.__abyssHalo=halo;n.__abyssHaloHost=o;return halo}catch{return null}}
function ensureCrosshair(){let el=document.querySelector('[data-abyss="crosshair"]');if(el)return el;const host=$('graph')||document.body;el=document.createElement('div');el.className='abyss-crosshair';el.dataset.abyss='crosshair';el.setAttribute('aria-hidden','true');el.style.cssText='position:absolute;width:46px;height:46px;margin:0;pointer-events:none;z-index:7;display:none;transform:translate(-50%,-50%);border:2px solid rgba(255,255,255,.95);border-radius:50%;box-shadow:0 0 0 6px rgba(127,227,255,.18),0 0 18px rgba(127,227,255,.65),inset 0 0 12px rgba(127,227,255,.25)';host.appendChild(el);return el}
function positionCrosshair(){const el=document.querySelector('[data-abyss="crosshair"]');if(!el)return;const g=window.__gpGraph;if(!selected||!g||typeof g.graph2ScreenCoords!=='function'){el.style.display='none';return}const x=Number(selected.x),y=Number(selected.y),z=Number(selected.z);if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(z)){el.style.display='none';return}let p=null;try{p=g.graph2ScreenCoords(x,y,z)}catch{el.style.display='none';return}if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y)){el.style.display='none';return}el.style.display='block';el.style.left=Math.round(p.x)+'px';el.style.top=Math.round(p.y)+'px'}
function ensureLabel(n){const wrap=$('labels');if(!wrap)return null;const id=String(n.id);let el=wrap.querySelector('[data-node-label="'+CSS.escape(id)+'"]');if(!el){el=document.createElement('div');el.className='node-label';el.dataset.nodeLabel=id;el.innerHTML='<span class="dot"></span><span class="text"></span>';wrap.appendChild(el)}const c=NODE_COLORS[n.kind]||NODE_COLORS.actor;el.querySelector('.text').textContent=String(n.label||n.name||n.title||n.id||'Entity');el.querySelector('.dot').style.background=c;el.querySelector('.dot').style.boxShadow='0 0 8px '+c;el.style.borderColor=c;el.style.display='block';return el}
function syncLabels(){const wrap=$('labels'),g=window.__gpGraph;if(!wrap||!g||typeof g.graph2ScreenCoords!=='function')return;if(dialog){wrap.style.visibility='hidden';wrap.style.opacity='0';return}wrap.style.visibility='visible';wrap.style.opacity='1';const live=new Set();for(const n of active.nodes){const el=ensureLabel(n);if(!el)continue;const x=Number(n.x),y=Number(n.y),z=Number(n.z);if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(z)){el.style.visibility='hidden';continue}let p;try{p=g.graph2ScreenCoords(x,y,z)}catch{el.style.visibility='hidden';continue}if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y)){el.style.visibility='hidden';continue}live.add(String(n.id));el.style.left=Math.round(p.x)+'px';el.style.top=Math.round(p.y-28)+'px';el.style.visibility=(p.x>-250&&p.x<window.innerWidth+250&&p.y>-100&&p.y<window.innerHeight+100)?'visible':'hidden'}Array.from(wrap.children).forEach(el=>{if(!live.has(el.dataset.nodeLabel))el.style.display='none'})}
function startLabelLoop(){cancelAnimationFrame(labelFrame);const loop=()=>{syncLabels();labelFrame=requestAnimationFrame(loop)};loop()}
/* OPTION D Abyss Current: major hubs + high-mention nodes breathe slowly via the
   halo shell only (core positions stay put). Fully static under prefers-reduced-motion. */
function startAbyssPulse(){cancelAnimationFrame(pulseFrame);if(reducedMotion())return;const t0=performance.now();const tick=()=>{try{const t=(performance.now()-t0)/1000;for(const n of active.nodes){const halo=ensureHalo(n);if(!halo||!halo.scale||typeof halo.scale.setScalar!=='function')continue;const hot=isMajor(n)||(Number(n.mentions)||0)>=pulseThreshold;halo.scale.setScalar(hot?ABYSS.haloScale+.32*Math.sin(t*1.4+(Number(n.x)||0)*.01):ABYSS.haloScale)}}catch{}pulseFrame=requestAnimationFrame(tick)};tick()}
function close(){dialog=false;selected=null;const d=$('details');if(d){d.classList.remove('open');d.style.display='none';d.style.pointerEvents='none';d.setAttribute('aria-hidden','true')}const wrap=$('labels');if(wrap){wrap.style.visibility='visible';wrap.style.opacity='1'}const xh=document.querySelector('[data-abyss="crosshair"]');if(xh)xh.style.display='none';paused=false;try{window.__gpGraph.resumeAnimation();window.__gpGraph.d3ReheatSimulation()}catch{}styles()}
function sourceCard(e){enrichEvidence(e);const u=resolveUrl(e);const title=String(e?.title||'Public intelligence record');return'<article class="source-card"><div class="source-head"><b>'+esc(e.source||'Public source')+'</b>'+(e.time?'<em>'+esc(e.time)+'</em>':'')+'</div><strong>'+esc(title)+'</strong>'+(e.summary?'<p>'+esc(e.summary)+'</p>':'')+(u?'<a class="source-link" href="'+esc(u)+'" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">OPEN ORIGINAL SOURCE ↗</a>':'<button class="source-link source-resolve" type="button" data-title="'+esc(title)+'" data-source="'+esc(e.source||'')+'">OPEN ORIGINAL SOURCE ↗</button>')+'</article>'}
function show(n){if(!n)return;if(dialog&&selected?.id===n.id)return;close();selected=n;dialog=true;paused=true;orbit=false;cancelAnimationFrame(orbitFrame);$('orbit')?.classList.remove('active');try{window.__gpGraph.pauseAnimation()}catch{}controls=false;$('controls').classList.add('collapsed');$('control-toggle').textContent='☰ OPEN FILTERS';$('control-toggle').setAttribute('aria-expanded','false');const wrap=$('labels');if(wrap){wrap.style.visibility='hidden';wrap.style.opacity='0'}positionCrosshair();const d=$('details');d.style.display='block';d.style.pointerEvents='auto';d.setAttribute('aria-hidden','false');const con=related(n),by=new Map(active.nodes.map(x=>[x.id,x])),all=[],seen=new Set();const add=e=>{enrichEvidence(e);const k=resolveUrl(e)||e?.title;if(e&&k&&!seen.has(k)){seen.add(k);all.push(e)}};n.evidence.forEach(add);con.forEach(e=>(e.evidence||[]).forEach(add));let h='<div class="title">'+esc(n.label)+'</div><div class="meta">NETWORK ENTITY · '+esc(n.kind.toUpperCase())+'</div><div class="chips"><span>'+con.length+' connections</span><span>'+Number(n.mentions||0)+' mentions</span><span>'+all.length+' evidence records</span></div><div class="method">'+esc(base.method)+'</div><div class="section"><b>WHY THIS NODE IS CONNECTED</b>';if(!con.length)h+='<p class="muted">No evidence-backed relationship is currently published for this node.</p>';else h+='<div class="evidence">'+con.slice(0,12).map(e=>{const id=peer(e,n.id),p=by.get(id),ev=e.evidence||[];return'<article class="relation" style="border-left:3px solid '+esc(edgeColor(e))+'"><div class="relation-title"><strong>'+esc(p?.label||id)+'</strong><span>'+ev.length+' source records</span></div><div class="reason"><b>Connection basis:</b> '+esc(e.relationship)+'</div>'+(e.types?.length?'<div class="type-line">SIGNALS · '+esc(e.types.join(' · '))+'</div>':'')+(ev.length?ev.slice(0,4).map(sourceCard).join(''):'<div class="no-evidence">No source attached to this edge.</div>')+'</article>'}).join('')+'</div>';h+='</div><div class="section"><b>SOURCES FOR THIS NODE</b><div class="evidence">'+(all.length?all.slice(0,16).map(sourceCard).join(''):'<p class="muted">No directly attached source records.</p>')+'</div></div>';$('detail').innerHTML=h;$('details').classList.add('open');$('close').focus();styles()}
function render(){
  const view=window.IntelligenceWebFilters.project(base,{query,category:filter,period});
  active={nodes:view.nodes,links:view.links};
  close();
  for(const n of active.nodes){delete n.__abyssHalo;delete n.__abyssHaloHost}
  $('labels').innerHTML='';
  active.nodes.forEach(ensureLabel);
  window.__gpGraph.graphData(active);
  styles();
  clearTimeout(fitTimer);
  fitTimer=setTimeout(()=>{if(active.nodes.length){try{window.__gpGraph.zoomToFit(700,90)}catch{}}syncLabels()},450);
  const range=period==='all'?'all available dates':`last ${period} hours`;
  pulseThreshold=view.nodes.reduce((m,n)=>Math.max(m,Number(n.mentions)||0),0)*.55;
  $('stats').innerHTML='<b>'+view.focus.length+'</b> matching entities · <b>'+active.nodes.length+'</b> visible · <b>'+active.links.length+'</b> evidence-backed connections · '+range+' · updated '+esc(base.updatedAt||'unknown');
  $('trend').textContent=period==='all'?'All available source dates':'Only source records published in the last '+period+' hours; undated records excluded.';
  $('node-select').innerHTML='<option value="">'+(view.focus.length?'Select a matching entity…':'No matching entities')+'</option>'+view.focus.map(n=>'<option value="'+esc(n.id)+'">'+esc(n.label)+'</option>').join('');
  $('node-select').disabled=!view.focus.length;
  document.querySelectorAll('.filter').forEach(b=>{const on=b.dataset.kind===filter;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});
  document.querySelectorAll('.period').forEach(b=>{const on=b.dataset.period===period;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});
}
if(typeof ForceGraph3D!=='function')throw Error('3D graph library failed to load');
const flowCount=()=>(relationships&&!paused&&!reducedMotion())?2:0;
const graphBuilder=new ForceGraph3D($('graph'),{controlType:'orbit',rendererConfig:{antialias:true,alpha:true,powerPreference:'high-performance'}}).backgroundColor('#020a12').showNavInfo(false).nodeId('id').nodeRelSize(6).nodeVal(n=>abyssSize(n,null,false)).nodeLabel(n=>'<b>'+esc(n.label)+'</b><br>'+esc(n.kind)+' · '+n.mentions+' mentions').nodeColor(n=>NODE_COLORS[n.kind]||NODE_COLORS.actor).linkColor(edgeColor).linkOpacity(.9).linkWidth(abyssLinkWidth).linkDirectionalArrowLength(5.5).linkDirectionalArrowRelPos(1).linkDirectionalArrowColor(edgeColor).linkDirectionalParticles(flowCount).linkDirectionalParticleWidth(3.2).linkDirectionalParticleSpeed(.008).enableNodeDrag(true).onNodeClick(show).d3VelocityDecay(.65).d3AlphaDecay(.08).warmupTicks(100).cooldownTicks(180);window.__gpGraph=graphBuilder;
window.addEventListener('resize',()=>{graphBuilder.width(window.innerWidth).height(window.innerHeight);syncLabels()});
try{graphBuilder.d3Force('charge').strength(-650).distanceMax(1500);graphBuilder.d3Force('link').distance(e=>Math.max(120,210-(Number(e.weight)||1)*10))}catch{}
const details=$('details'),closeBtn=$('close');details.addEventListener('pointerdown',e=>e.stopPropagation(),true);details.addEventListener('click',e=>e.stopPropagation());details.addEventListener('touchstart',e=>e.stopPropagation(),{capture:true,passive:true});closeBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();close();$('node-select').value='';});details.addEventListener('click',e=>{const a=e.target.closest?.('.source-resolve');if(!a)return;e.preventDefault();e.stopPropagation();const t=normTitle(a.dataset.title),s=normTitle(a.dataset.source),u=liveBySourceTitle.get(s+'|'+t)||liveByTitle.get(t)||'';if(u)window.open(u,'_blank','noopener,noreferrer');else{a.textContent='SOURCE URL NOT AVAILABLE';a.disabled=true}},{capture:true});$('clear').onclick=()=>{$('search').value='';query='';render()};$('refresh').onclick=()=>load().then(x=>{base=x;render()}).catch(showLoadingError);$('search').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.kind||'all';document.querySelectorAll('.filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render()});$('reset').onclick=()=>{filter='all';period='all';query='';$('search').value='';document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b.dataset.kind==='all');b.setAttribute('aria-pressed',String(b.dataset.kind==='all'))});render()};$('orbit').onclick=function(){orbit=!orbit;this.classList.toggle('active',orbit);this.setAttribute('aria-pressed',String(orbit));cancelAnimationFrame(orbitFrame);if(orbit){let a=0;const go=()=>{if(!orbit||paused)return;window.__gpGraph.cameraPosition({x:720*Math.sin(a),y:150,z:720*Math.cos(a)},undefined,0);a+=.0025;orbitFrame=requestAnimationFrame(go)};go()}};$('flow').onclick=function(){relationships=!relationships;this.classList.toggle('active',relationships);this.setAttribute('aria-pressed',String(relationships));window.__gpGraph.linkVisibility(relationships);window.__gpGraph.linkDirectionalParticles(flowCount)};document.querySelectorAll('.filter,.period').forEach(x=>x.setAttribute('aria-pressed',String(x.classList.contains('active'))));document.querySelectorAll('.period').forEach(b=>b.onclick=()=>{period=b.dataset.period||'all';document.querySelectorAll('.period').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render()});$('node-select').onchange=e=>show(active.nodes.find(n=>n.id===e.target.value));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog){close();$('node-select').focus()}});render();startLabelLoop();startAbyssPulse();ensureCrosshair();$('details').style.pointerEvents='none';$('details').setAttribute('aria-hidden','true');hideLoading();setInterval(()=>{if(!document.hidden&&!dialog)load().then(x=>{if(x.updatedAt!==base.updatedAt){base=x;render()}}).catch(e=>console.warn('[Intelligence Web refresh]',e))},60000)}
$('stats').textContent='Loading evidence graph…';load().then(main).catch(showLoadingError);
})();
