(()=>{'use strict';
const SOURCES=['data/canonical_intelligence.json','data/intelligence_brain.json'];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const latest=e=>e?.timestamp||e?.published_at||e?.publishedAt||e?.time||e?.date||'';
const labelFor=(id,map)=>map.get(String(id))?.canonical_name||map.get(String(id))?.label||String(id||'Unknown');
const domainFor=e=>String(e?.event_type||'intelligence').replaceAll('_',' ');
function actorBucket(name){if(/united states|u\.s\.?|usa|american|washington|pentagon|white house/i.test(name))return 'UNITED STATES';if(/china|chinese|beijing|pla|people.s republic/i.test(name))return 'CHINA';return null}
function buildCanonical(data){const entities=new Map((Array.isArray(data.entities)?data.entities:[]).map(x=>[String(x.id),x]));const evById=new Map((Array.isArray(data.evidence)?data.evidence:[]).map(x=>[String(x.id),x]));const out={'UNITED STATES':[],'CHINA':[]};for(const e of Array.isArray(data.events)?data.events:[]){for(const aid of Array.isArray(e.actor_ids)?e.actor_ids:[]){const actor=entities.get(String(aid));const bucket=actorBucket(actor?.canonical_name||'');if(!bucket)continue;const targets=(Array.isArray(e.target_ids)?e.target_ids:[]).map(id=>labelFor(id,entities)).filter(Boolean);const evidence=(Array.isArray(e.evidence_ids)?e.evidence_ids:[]).map(id=>evById.get(String(id))).filter(Boolean);const primary=evidence[0]||{};out[bucket].push({title:e.title||e.action||'Action signal',action:e.action||domainFor(e),target:targets.join(', ')||'Target not explicitly resolved',domain:domainFor(e),confidence:Number(e.confidence)||0,relevance:Number(e.strategic_relevance)||Number(e.geopolitical_relevance)||0,time:latest(e)||latest(primary),source:primary.source||'Source',url:primary.url||'',eventId:e.id});}}
for(const k of Object.keys(out)){const seen=new Set();out[k]=out[k].filter(x=>{const id=x.eventId||x.title;if(seen.has(id))return false;seen.add(id);return true}).sort((a,b)=>(b.relevance-a.relevance)||(b.confidence-a.confidence)||String(b.time).localeCompare(String(a.time))).slice(0,8)}return out}
function buildFallback(data){const out={'UNITED STATES':[],'CHINA':[]};for(const n of Array.isArray(data.nodes)?data.nodes:[]){const body=[n.label,n.name,n.country,n.group,n.summary,n.description].filter(Boolean).join(' ');const bucket=actorBucket(body);if(!bucket)continue;for(const e of Array.isArray(n.evidence)?n.evidence:[]){if(!/announced|approved|imposed|sanction|deployed|struck|attacked|launched|restricted|banned|tariff|export control|exercise|drill|patrol|missile|troops|forces|diplomatic|negotiat|agreement|meeting|warning|election|stimulus|regulation|investigation|arrested|seized|blocked|withdrew|recognized|signed|pledged/i.test([e.title,e.summary,e.description].filter(Boolean).join(' ')))continue;out[bucket].push({title:e.title||n.label,action:'action signal',target:'Not explicitly resolved',domain:'evidence',confidence:0,relevance:0,time:e.time||e.published_at||e.date||'',source:e.source||'Source',url:e.url||''})}}return out}
function install(primary,fallback){if(document.getElementById('aegis-action-panel'))return;const collected=primary&&Array.isArray(primary.events)?buildCanonical(primary):buildFallback(fallback||{});const style=document.createElement('style');style.textContent=`#aegis-action-panel{position:fixed;left:14px;bottom:78px;z-index:80;width:min(700px,calc(100vw - 28px));background:rgba(2,8,13,.96);border:1px solid #193244;border-radius:14px;padding:11px;box-shadow:0 18px 60px #000;backdrop-filter:blur(16px);font:10px system-ui,sans-serif}#aegis-action-panel .ah{display:flex;justify-content:space-between;align-items:center;gap:8px;color:#39ff88;font-weight:950;letter-spacing:.12em}.as{color:#8198aa;font-size:8px;margin-top:3px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.actor{border:1px solid #193244;border-radius:9px;padding:8px;min-width:0}.actor h4{margin:0 0 5px;color:#eaf4ff;font-size:9px}.item{border-top:1px solid #132733;padding:7px 0}.item:first-child{border-top:0}.item b{display:block;color:#dcecf5;font-size:8px;line-height:1.35}.meta{display:block;color:#8198aa;font-size:7px;margin-top:3px;line-height:1.4}.tag{display:inline-block;color:#39ff88;border:1px solid #28563f;border-radius:5px;padding:1px 4px;margin-right:4px;text-transform:uppercase}.item a{color:#39ff88;text-decoration:none}.empty{color:#8198aa;font-size:8px;padding:6px 0}@media(max-width:700px){#aegis-action-panel{left:8px;bottom:55px;width:calc(100vw - 16px)}.cols{grid-template-columns:1fr}}`;document.head.appendChild(style);const p=document.createElement('section');p.id='aegis-action-panel';const render=(key,label)=>{const rows=collected[key]||[];return `<div class="actor"><h4>${label} // VERIFIED ACTION MODEL</h4>${rows.length?rows.map(x=>`<div class="item"><b>${esc(x.action)} → ${esc(x.target)}</b><span class="meta"><span class="tag">${esc(x.domain)}</span>${esc(x.title)}${x.time?' · '+esc(x.time):''} · confidence ${Math.round((x.confidence||0)*100)}%${x.relevance?' · strategic '+Math.round(x.relevance*100)+'%':''}${x.url?` · <a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">EVIDENCE</a>`:''}</span></div>`).join(''):'<div class="empty">No explicit actor-attributed action events currently available.</div>'}</div>`};const total=(collected['UNITED STATES']?.length||0)+(collected.CHINA?.length||0);p.innerHTML=`<div class="ah"><span>STRATEGIC ACTION INTELLIGENCE</span><span>${total} EVENTS</span></div><div class="as">Actor → action → target attribution from canonical evidence. Co-mention alone is not treated as action.</div><div class="cols">${render('UNITED STATES','UNITED STATES')}${render('CHINA','CHINA')}</div>`;document.body.appendChild(p)}
async function load(){let canonical=null,fallback=null;for(const src of SOURCES){try{const r=await fetch(src,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();if(src.includes('canonical'))canonical=d;else fallback=d}catch{}}install(canonical,fallback)}
load();
})();