(()=>{'use strict';
const SOURCES=['data/canonical_intelligence.json','data/intelligence_brain.json'];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const latest=e=>e?.timestamp||e?.published_at||e?.publishedAt||e?.time||e?.date||'';
const labelFor=(id,map)=>map.get(String(id))?.canonical_name||map.get(String(id))?.label||String(id||'Unknown');
const domainFor=e=>String(e?.event_type||'intelligence').replaceAll('_',' ');
function actorBucket(name){if(/united states|u\.s\.?|usa|american|washington|pentagon|white house/i.test(name))return 'UNITED STATES';if(/china|chinese|beijing|pla|people.s republic/i.test(name))return 'CHINA';return null}
function buildCanonical(data){const entities=new Map((Array.isArray(data.entities)?data.entities:[]).map(x=>[String(x.id),x]));const evById=new Map((Array.isArray(data.evidence)?data.evidence:[]).map(x=>[String(x.id),x]));const out={'UNITED STATES':[],'CHINA':[]};for(const e of Array.isArray(data.events)?data.events:[]){for(const aid of Array.isArray(e.actor_ids)?e.actor_ids:[]){const actor=entities.get(String(aid));const bucket=actorBucket(actor?.canonical_name||'');if(!bucket)continue;const targets=(Array.isArray(e.target_ids)?e.target_ids:[]).map(id=>labelFor(id,entities)).filter(Boolean);const evidence=(Array.isArray(e.evidence_ids)?e.evidence_ids:[]).map(id=>evById.get(String(id))).filter(Boolean);const primary=evidence[0]||{};out[bucket].push({title:e.title||e.action||'Action signal',action:e.action||domainFor(e),target:targets.join(', ')||'Target not explicitly resolved',domain:domainFor(e),confidence:Number(e.confidence)||0,relevance:Number(e.strategic_relevance)||Number(e.geopolitical_relevance)||0,time:latest(e)||latest(primary),source:primary.source||'Source',url:primary.url||'',eventId:e.id});}}
for(const k of Object.keys(out)){const seen=new Set();out[k]=out[k].filter(x=>{const id=x.eventId||x.title;if(seen.has(id))return false;seen.add(id);return true}).sort((a,b)=>(b.relevance-a.relevance)||(b.confidence-a.confidence)||String(b.time).localeCompare(String(a.time))).slice(0,8)}return out}
function buildFallback(data){const out={'UNITED STATES':[],'CHINA':[]};for(const n of Array.isArray(data.nodes)?data.nodes:[]){const body=[n.label,n.name,n.country,n.group,n.summary,n.description].filter(Boolean).join(' ');const bucket=actorBucket(body);if(!bucket)continue;for(const e of Array.isArray(n.evidence)?n.evidence:[]){if(!/announced|approved|imposed|sanction|deployed|struck|attacked|launched|restricted|banned|tariff|export control|exercise|drill|patrol|missile|troops|forces|diplomatic|negotiat|agreement|meeting|warning|election|stimulus|regulation|investigation|arrested|seized|blocked|withdrew|recognized|signed|pledged/i.test([e.title,e.summary,e.description].filter(Boolean).join(' ')))continue;out[bucket].push({title:e.title||n.label,action:'action signal',target:'Not explicitly resolved',domain:'evidence',confidence:0,relevance:0,time:e.time||e.published_at||e.date||'',source:e.source||'Source',url:e.url||''})}}return out}
function install(primary,fallback){/* Strategic action overlay disabled: was covering the Intelligence Web graph with no close control. */return;}
async function load(){let canonical=null,fallback=null;for(const src of SOURCES){try{const r=await fetch(src,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();if(src.includes('canonical'))canonical=d;else fallback=d}catch{}}install(canonical,fallback)}
load();
})();
