(()=>{'use strict';
const DATA='data/canonical_intelligence.json';
const FALLBACK='data/intelligence_brain.json';
const C={military:'#ff8a3d',economic:'#ffc857',diplomatic:'#39ff88',technology:'#8b7cff',security:'#5da8ff',political:'#d28cff',maritime:'#35d7c4',energy:'#ffcf66',cyber:'#b88cff',default:'#8aa0b2'};
let actions=[],root,svg,raf=0;
function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function aliases(s){const v=norm(s),out=new Set([v]);if(['united states','u.s.','u.s.a.','usa','american','america','washington','white house','pentagon'].includes(v)){['united states','u.s.','u.s.a.','usa','american','america','washington','white house','pentagon'].forEach(x=>out.add(x))}if(['china','chinese','beijing','pla','people’s republic of china','people\'s republic of china','ccp'].includes(v)){['china','chinese','beijing','pla','people’s republic of china','people\'s republic of china','ccp'].forEach(x=>out.add(x))}return [...out]}
function ensure(){if(root)return;root=document.createElement('div');root.id='gp-action-flow-layer';root.style.cssText='position:fixed;inset:0;z-index:7;pointer-events:none;overflow:hidden';svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.style.cssText='position:absolute;inset:0;width:100%;height:100%;overflow:visible';root.appendChild(svg);document.body.appendChild(root)}
function collectCanonical(d){const entities=new Map((d.entities||[]).filter(e=>e&&e.id).map(e=>[String(e.id),e]));actions=[];(d.events||[]).forEach(ev=>{if(!ev||!Array.isArray(ev.actor_ids)||!Array.isArray(ev.target_ids)||!ev.actor_ids.length||!ev.target_ids.length)return;for(const aid of ev.actor_ids){const actor=entities.get(String(aid));if(!actor)continue;for(const tid of ev.target_ids){const target=entities.get(String(tid));if(!target||String(aid)===String(tid))continue;actions.push({actor:actor.canonical_name||actor.name||actor.label||aid,target:target.canonical_name||target.name||target.label||tid,action:ev.action||ev.event_type||'action',category:String(ev.event_type||'security').replace('_action','').replace('_activity','').toLowerCase(),importance:Number(ev.score||ev.strategic_relevance||ev.confidence||1),confidence:Number(ev.confidence||0),ts:ev.timestamp||'',title:ev.title||''})}}});actions.sort((a,b)=>b.importance-a.importance);actions=actions.slice(0,40)}
function collectFallback(d){actions=[];(d.nodes||[]).forEach(n=>(n.actions||[]).forEach(a=>{if(!a||!a.actor||!a.target||!a.action||!Array.isArray(a.evidence)||!a.evidence.length)return;actions.push({actor:n.label||a.actor,target:a.target,action:a.action,category:String(a.category||'security').toLowerCase(),importance:Number(a.importance||a.weight||1),confidence:Number(a.confidence||0),evidence:a.evidence})}));actions.sort((a,b)=>b.importance-a.importance);actions=actions.slice(0,40)}
function labelMap(){const m=new Map();document.querySelectorAll('.gp-label').forEach(e=>m.set(norm(e.textContent),e));return m}
function resolveLabel(map,name){for(const a of aliases(name))if(map.has(a))return map.get(a);return map.get(norm(name))}
function draw(){raf=0;ensure();while(svg.firstChild)svg.removeChild(svg.firstChild);const map=labelMap();let i=0;for(const a of actions){const s=resolveLabel(map,a.actor),t=resolveLabel(map,a.target);if(!s||!t||s===t)continue;const sr=s.getBoundingClientRect(),tr=t.getBoundingClientRect(),x1=sr.left+sr.width/2,y1=sr.top+sr.height/2,x2=tr.left+tr.width/2,y2=tr.top+tr.height/2,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);if(len<35)continue;const color=C[a.category]||C.default,id='gpaf'+(++i),defs=document.createElementNS('http://www.w3.org/2000/svg','defs'),mk=document.createElementNS('http://www.w3.org/2000/svg','marker');mk.id=id;mk.setAttribute('markerWidth','7');mk.setAttribute('markerHeight','7');mk.setAttribute('refX','6');mk.setAttribute('refY','3.5');mk.setAttribute('orient','auto');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M0,0 L7,3.5 L0,7 Z');path.setAttribute('fill',color);mk.appendChild(path);defs.appendChild(mk);svg.appendChild(defs);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);line.setAttribute('stroke',color);line.setAttribute('stroke-width',String(Math.min(3,1+Math.log1p(a.importance))));line.setAttribute('stroke-opacity',String(.48+Math.min(.3,a.confidence*.3)));line.setAttribute('stroke-dasharray','6 7');line.setAttribute('marker-end',`url(#${id})`);svg.appendChild(line);const g=document.createElementNS('http://www.w3.org/2000/svg','g'),tx=x1+dx*.5,ty=y1+dy*.5,bg=document.createElementNS('http://www.w3.org/2000/svg','rect');bg.setAttribute('x',tx-60);bg.setAttribute('y',ty-10);bg.setAttribute('width','120');bg.setAttribute('height','20');bg.setAttribute('rx','7');bg.setAttribute('fill','#02070c');bg.setAttribute('fill-opacity','.92');bg.setAttribute('stroke',color);bg.setAttribute('stroke-opacity','.55');const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',tx);text.setAttribute('y',ty+3);text.setAttribute('text-anchor','middle');text.setAttribute('fill','#eaf4ff');text.setAttribute('font-size','8');text.setAttribute('font-family','system-ui,sans-serif');text.setAttribute('font-weight','700');text.textContent=a.action.length>28?a.action.slice(0,27)+'…':a.action;g.appendChild(bg);g.appendChild(text);svg.appendChild(g)}}
function queue(){if(!raf)raf=requestAnimationFrame(draw)}
async function load(){try{let r=await fetch(DATA+'?v='+Date.now(),{cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d.events)&&Array.isArray(d.entities)){collectCanonical(d);queue();return}}r=await fetch(FALLBACK+'?v='+Date.now(),{cache:'no-store'});if(r.ok){collectFallback(await r.json());queue()}}catch(e){console.warn('Action flow layer unavailable',e)}}
function init(){load();new MutationObserver(queue).observe(document.getElementById('graph')||document.body,{childList:true,subtree:true});addEventListener('resize',queue);setInterval(queue,500)}
init();
/* Boot watchdog: the graph must never remain on a permanent loading screen. */
function hideLoading(){const l=document.getElementById('loading');if(l){l.style.display='none';l.setAttribute('aria-hidden','true')}}
function showBootError(message){const l=document.getElementById('loading');if(!l)return;l.style.display='grid';l.innerHTML='<div style="max-width:520px;padding:24px;text-align:center"><b style="color:#39ff88">INTELLIGENCE WEB</b><div style="margin-top:10px;color:#eaf4ff">'+String(message).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))+'</div><button onclick="location.reload()" style="margin-top:14px">RETRY</button></div>'}
async function bootWatchdog(){await new Promise(r=>setTimeout(r,2200));const l=document.getElementById('loading');if(!l||l.style.display==='none')return;try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);const r=await fetch(FALLBACK+'?boot='+Date.now(),{cache:'no-store',signal:c.signal});clearTimeout(timer);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.nodes))throw Error('invalid brain data');window.__GP_INTELLIGENCE_DATA__=d;hideLoading();const s=document.getElementById('stats');if(s)s.textContent='LIVE DATA READY • '+d.nodes.length+' source-backed nodes • '+(Array.isArray(d.edges)?d.edges.length:0)+' relationships';window.__GP_INTELLIGENCE_READY__=true}catch(e){showBootError('The intelligence graph renderer did not finish loading. '+(e.name==='AbortError'?'Data request timed out.':e.message))}}
bootWatchdog();
})();
